fix: Add some software-terms words that start with "un"
streetsidesoftware/cspell-dicts pull request #3446
Opened 2024-08-07 08:38 UTC by ssbarnea

# Add/Fix Dictionary

Dictionary: software-terms

## Description

- add missing software-terms
- lowercase few terms
- correct sorting
- add correction for instantiatable

- https://english.stackexchange.com/questions/337696/what-is-the-proper-word-for-something-that-can-be-instantiated

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

Fixes: #3129
Fixes: https://github.com/streetsidesoftware/cspell/issues/5286
Needs: #3617

2024-08-07 08:39 UTC, ssbarnea commented
That things with "4 workflows awaiting approval" does not seem very welcoming,... and I even contributed previously. Maybe a tune in settings would be possible?

2024-08-07 15:55 UTC, Jason3S commented
> @Jason3S That things with "4 workflows awaiting approval" does not seem very welcoming,... and I even contributed previously. Maybe a tune in settings would be possible? ;)

I would be happy to add you as a contributor. 

The default security settings have gotten stricter over time.

2024-08-07 16:12 UTC, Jason3S requested changes
@ssbarnea,

Thank you for the additions and taking the time to do it.

2024-08-07 16:12 UTC, Jason3S commented on dictionaries/en_US/src/additional_words.txt
> +unaggregated
Please add these words (all the ones you added) to [coding-terms](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/coding-terms.txt).

This dictionary is for US English words, general computing/coding terms are better of in the software terms dictionary. That way, those that do not use US English will also get the benefit.

2024-08-07 16:17 UTC, Jason3S commented
@ssbarnea,

It is ok to just add words to the end of the file, it will get sorted automatically.

2024-08-21 09:50 UTC, Jason3S commented
@ssbarnea,

Would you like some help with this PR?

2024-08-21 15:00 UTC, ssbarnea commented
@Jason3S no, is just that I got sidetracked by other activities. I just seen the invite from you a minute ago but it expired.

2024-08-21 18:08 UTC, Jason3S commented
@ssbarnea,

> I just seen the invite from you a minute ago but it expired.

I'll send it again.

2024-10-01 12:43 UTC, ssbarnea commented
@Jason3S Something unexpected happened when I updated this PR. I seen failing to run because pnpm lock was out of sync with the package.json, and I did not touch those files.

See https://github.com/streetsidesoftware/cspell-dicts/actions/runs/11125090808/job/30912037317

I have experience using reqs and lock files with npm and yarn, but not pnpm but I assume that they would work very similarly. The only case where this would happen is if someone would push a change bypassing the GHA pipelines, which I doubt is the case.

2024-10-01 16:39 UTC, Jason3S commented
> @Jason3S Something unexpected happened when I updated this PR. I seen failing to run because pnpm lock was out of sync with the package.json, and I did not touch those files.
> 
> See https://github.com/streetsidesoftware/cspell-dicts/actions/runs/11125090808/job/30912037317
> 
> I have experience using reqs and lock files with npm and yarn, but not pnpm but I assume that they would work very similarly. The only case where this would happen is if someone would push a change bypassing the GHA pipelines, which I doubt is the case.
> 
> Maybe there is something incorrectly configured on GHA that allowed this to happen, or some caching went nuts?
> 
> As the issue reproduced locally, I raised #3617 which should address this issue.

Thank you. I hadn't realize the build was broken. The last publish PR had a stale lock file, causing it to fail. #3612 had an updated package.json, but not an updated pnpm-lock.yaml.

2024-10-01 16:41 UTC, Jason3S approved these changes

2024-10-01 16:41 UTC, Jason3S commented
@ssbarnea,

Thank you for fixing the files.

2024-10-01 16:44 UTC, merged